# Generated by Django 4.1.7 on 2023-03-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentteacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentteacher',
            options={'verbose_name': 'Студент-Учитель', 'verbose_name_plural': 'Студент-Учителя'},
        ),
    ]
