# Generated by Django 4.1.7 on 2023-03-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
